version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: cargo watch -x run
    volumes:
      - ${PWD}/mainman:/usr/mainman/mainman
      - ${PWD}/Cargo.toml:/usr/mainman/Cargo.toml
      - ${PWD}/stripe:/usr/mainman/stripe
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug

  nginx:
    command: nginx -g "daemon off;"
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
    volumes:
      - ${PWD}/config/nginx/development/localhost.crt:/etc/ssl/localhost.crt
      - ${PWD}/config/nginx/development/localhost.key:/etc/ssl/localhost.key
      - ${PWD}/config/nginx/development/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/config/certbot/conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    volumes:
      - ${PWD}/config/certbot/conf:/etc/letsencrypt
      - ${PWD}/config/certbot/www:/var/www/certbot
