version: '3'
services:
  backend:
    build: .
    depends_on:
      - db
      - cache
    restart: unless-stopped
    command: hallussa-backend
    ports:
      - 8080:8080

  db:
    build: ./db
    expose:
      - 5432
    restart: unless-stopped
    env_file:
      - ./.env
      - ./db.env

  cache:
    image: redis:latest
