version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: cargo watch -x run
    volumes:
      - ./mainman:/usr/mainman/mainman
      - ./Cargo.toml:/usr/mainman/Cargo.toml
      - ./stripe:/usr/mainman/stripe
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=mainman=debug,actix_web=info

  nginx:
    command: nginx -g "daemon off;"
    build:
      context: ./config/nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
    volumes:
      - ./config/nginx/development/localhost.crt:/etc/ssl/localhost.crt
      - ./config/nginx/development/localhost.key:/etc/ssl/localhost.key
      - ./config/nginx/development/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/development/shared_location.conf:/etc/nginx/shared_location.conf
      - ./config/certbot/conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
