version: '3'
services:
  backend:
    build: .
    depends_on:
      - db
      - cache
    restart: unless-stopped
    command: hallussa-backend
    ports:
      - 8080:8080
    env_file:
      - ./.env

  db:
    build: ./db
    expose:
      - 5432
    restart: unless-stopped
    env_file:
      - ./.env
      - ./db/.env

  migrate:
    build:
      context: ./db
      dockerfile: migrate.Dockerfile
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - ./db/.env
    volumes:
      - ./db/migrations:/migrate/migrations:ro
      - ${PWD}/src/schema.rs:/migrate/src/schema.rs
      - ${PWD}/diesel.toml:/migrate/diesel.toml

  cache:
    image: redis:latest
