version: "3"
services:
  backend:
    build: .
    depends_on:
      - db
      - redis
    restart: unless-stopped
    command: mainman
    expose:
      - 8080
    env_file:
      - ./.env

  db:
    build: ./db
    expose:
      - 5432
    restart: unless-stopped
    env_file:
      - ./.env
      - ./db/.env

  migrate:
    build:
      context: ./db
      dockerfile: migrate.Dockerfile
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - ./db/.env
    volumes:
      - ${PWD}/db/scripts:/migrate/scripts:ro
      - ${PWD}/db/migrations:/migrate/migrations:ro
      - ${PWD}/mainman/src/schema.rs:/migrate/schema.rs
      - ${PWD}/diesel.toml:/migrate/diesel.toml

  redis:
    image: redis:latest

  nginx:
    build: ./config/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
    volumes:
      - ${PWD}/config/nginx/production/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/config/nginx/production/shared_location.conf:/etc/nginx/shared_location.conf
      - ${PWD}/config/certbot/conf:/etc/letsencrypt
      - ${PWD}/config/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ${PWD}/config/certbot/conf:/etc/letsencrypt
      - ${PWD}/config/certbot/www:/var/www/certbot

  redoc:
    image: redocly/redoc
    volumes:
      - ${PWD}/spec.yaml:/usr/share/nginx/html/spec.yaml
    expose:
      - 8000
    environment:
      - PORT=8000
      - PAGE_TITLE=Mainman
      - SPEC_URL=spec.yaml
