version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: systemfd --no-pid -s http::0.0.0.0:8080 -- cargo watch -x run
    volumes:
      - ./src:/usr/src/hallussa-backend/src

