version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: cargo watch -x run
    volumes:
      - ./src:/usr/src/mainman/src
      - ./Cargo.toml:/usr/src/mainman/Cargo.toml
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=mainman=debug,actix_web=info
