#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 <<-EOSQL
  CREATE USER mainman_client WITH PASSWORD '$DB_PASSWORD_CLIENT';
  REVOKE CONNECT ON DATABASE mainman FROM PUBLIC;
  GRANT CONNECT ON DATABASE mainman TO mainman_client;
  REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
  GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA public
  TO mainman_client;

  CREATE EXTENSION "uuid-ossp";
EOSQL
