[package]
name = "stripe"
version = "0.1.0"
authors = ["Touko Hallasmaa <hallasmaa.touko@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = { version = "3", features = ["rustls"]}
rustls = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
